# Generated by Django 3.2.6 on 2021-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
